modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Core.json" #optional
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Core/issues" #optional
displayURL="https://minecraft.curseforge.com/projects/ctd-core" #optional
authors="TheMasterGeneral" #optional
logoFile="logo-new.png" #optional
license="https://github.com/MasterGeneral156/CTD-Core/blob/1.16/LICENSE"
[[mods]] #mandatory
    modId="ctdcore" #mandatory
    version="2.0.6" #mandatory
    displayName="CTD Core" #mandatory
    description="A Library mod for mods created by TheMasterGeneral."
[[dependencies.ctdcore]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.ctdcore]]
    modId = "forge"
    mandatory = true
    versionRange = "[34,]"
    ordering = "NONE"
    side = "BOTH"