modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Core.json" #optional
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Core/issues" #optional
displayURL="https://minecraft.curseforge.com/projects/ctd-core" #optional
authors="TheMasterGeneral" #optional
logoFile="logo-new.png" #optional
[[mods]] #mandatory
    modId="ctdcore" #mandatory
    version="2.0.5" #mandatory
    displayName="CTD Core" #mandatory
    description="A Library mod for mods created by TheMasterGeneral."
[[dependencies.ctdcore]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.14.4]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.ctdcore]]
    modId = "forge"
    mandatory = true
    versionRange = "[28.1,]"
    ordering = "NONE"
    side = "BOTH"