modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Core.json" #optional
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Core/issues" #optional
displayURL="https://minecraft.curseforge.com/projects/ctd-core" #optional
authors="TheMasterGeneral" #optional
logoFile="logo-new.png" #optional
license="https://github.com/MasterGeneral156/CTD-Core/blob/1.19/LICENSE"
[[mods]] #mandatory
    modId="ctdcore" #mandatory
    version="2.2.0" #mandatory
    displayName="CTD Core" #mandatory
    description="A Library mod for mods created by TheMasterGeneral."