modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Core.json" #optional
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Core/issues" #optional
displayURL="https://minecraft.curseforge.com/projects/ctd-core" #optional
logoFile="textures/logo-new.png" #optional
authors="TheMasterGeneral" #optional
[[mods]] #mandatory
modId="ctdcore" #mandatory
version="2.0.3" #mandatory
displayName="CTD Core" #mandatory
description='''
A Library mod for mods created by TheMasterGeneral.'''