org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

## Mod Properties
mod_id=ctdcore
mod_build=ctd-core-forge
mod_name=CTD Core
mod_license=https://raw.githubusercontent.com/MasterGeneral156/CTD-Core/refs/heads/26.1/LICENSE
mod_version=1.21.11-2.9.5b
mod_group_id=com.themastergeneral.ctdcore
mod_authors=TheMasterGeneral
mod_description=A library mod for CTD Mods.
net.minecraftforge.gradle.merge-source-sets=true
