# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
# There are lots of things you can do with the mods.toml, and not all fields are included with this MDK
# References: https://github.com/MinecraftForge/MDKExamples

modLoader="javafml"
loaderVersion="[62,)"
license="${mod_license}"
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Core/issues" #optional
#clientSideOnly=true #optional, default=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/refs/heads/master/CTD-Core.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/ctd-core" #optional
logoFile="ctd-core.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional
#displayTest="MATCH_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION

description='''${mod_description}'''

[[dependencies.examplemod]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[62,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,26.2,)"
    ordering="NONE"
    side="BOTH"
